/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * #########################################################################
 * # .data # .bss # newlib heap # sizing pad # Imalloc arena #  MSP stack  #
 * #       #      #    512 B    #   0x1000   #               #             #
 * #########################################################################
 * ^ RAM start    ^ __libc_heap_start        ^ _end          ^ _sstack     ^ _estack
 * @endverbatim
 *
 * This implementation allocates strictly within [__libc_heap_start,
 * __libc_heap_end), the ._user_heap_stack heap block reserved by
 * '_Min_Heap_Size' in the linker script. That range belongs to newlib only:
 * micro T-Kernel's Imalloc region (sys_start.c) starts at the '_end' linker
 * symbol, which the linker script places after this whole block, so the two
 * allocators never overlap.
 * NOTE: the block is only _Min_Heap_Size = 0x200 = 512 bytes, sized for
 * T-Monitor output formatting only, not for general dynamic allocation.
 * NOTE: the check below is upper-bounded only. A negative 'incr' is not
 * validated and can move '__sbrk_heap_end' below '__libc_heap_start'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t __libc_heap_start; /* Symbol defined in the linker script */
  extern uint8_t __libc_heap_end; /* Symbol defined in the linker script */
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &__libc_heap_start;
  }

  /* Protect heap from growing past the reserved newlib heap block */
  if (__sbrk_heap_end + incr > &__libc_heap_end)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}
