 /**
 ******************************************************************************
 * @file    app_config.h
 * @author  GPM Application Team
 *
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef APP_CONFIG
#define APP_CONFIG

#include "arm_math.h"

#define USE_DCACHE

/*Defines: CMW_MIRRORFLIP_NONE; CMW_MIRRORFLIP_FLIP; CMW_MIRRORFLIP_MIRROR; CMW_MIRRORFLIP_FLIP_MIRROR;*/
#define CAMERA_FLIP CMW_MIRRORFLIP_NONE

#define ASPECT_RATIO_CROP       (1) /* Crop both pipes to nn input aspect ratio; Original aspect ratio kept */
#define ASPECT_RATIO_FIT        (2) /* Resize both pipe to NN input aspect ratio; Original aspect ratio not kept */
#define ASPECT_RATIO_FULLSCREEN (3) /* Resize camera image to NN input size and display a maximized image. See Doc/Build-Options.md#aspect-ratio-mode */
/* Preserve face geometry by taking the same centered square crop for the LCD
 * and YuNet pipes. FIT is intentionally not used because it stretches the
 * widescreen camera frame into a square and degrades face proportions. */
#define ASPECT_RATIO_MODE ASPECT_RATIO_CROP

/* Model Related Info */
#define POSTPROCESS_TYPE    POSTPROCESS_FD_YUNET_UI

#define COLOR_BGR (0)
#define COLOR_RGB (1)
#define COLOR_MODE    COLOR_RGB

/*
 * YuNet postprocessing configuration.
 *
 * IMG_SIZE / NB_KEYPOINTS / OUT_*_NB_BOXES are confirmed against the actual
 * generated Model/stai_network.h (12 outputs: cls/obj/bbox/kps x3 strides,
 * 40x40=1600 @stride8, 20x20=400 @stride16, 10x10=100 @stride32, kps width
 * 10 = 5 keypoints x2). Vendor/Postprocess/Inc/fd_yunet_anchors_{32,16,8}.h
 * (grid-cell anchor tables, included by app_postprocess_fd_yunet_ui.c) are
 * generated by tools/generate_yunet_anchors.py (see THIRD_PARTY_NOTICES.md).
 */
#define AI_FD_YUNET_PP_IMG_SIZE            (320)
#define AI_FD_YUNET_PP_NB_KEYPOINTS        (5)
#define AI_FD_YUNET_PP_OUT_32_NB_BOXES     (100)
#define AI_FD_YUNET_PP_OUT_16_NB_BOXES     (400)
#define AI_FD_YUNET_PP_OUT_8_NB_BOXES      (1600)
#define AI_FD_YUNET_PP_MAX_BOXES_LIMIT     (10)
/* Decode/NMS candidates down to the tracker update threshold. The tracker
 * requires 0.35 for a new face and uses 0.20 only to maintain an existing
 * spatially matching track. */
#define AI_FD_YUNET_PP_CONF_THRESHOLD      (0.20)
#define AI_FD_YUNET_PP_IOU_THRESHOLD       (0.5)

/* Display */
#define WELCOME_MSG_1         "yunetn_320_qdq_int8.onnx"
#define WELCOME_MSG_2         "Model Running in STM32 MCU internal memory"

#endif
