#ifndef MODEL_SIGNATURE_H
#define MODEL_SIGNATURE_H

#include <stdint.h>

typedef struct
{
  uint32_t offset;
  uint32_t expected;
} ModelSignatureWord;

/* Generated by tools/generate_model_signature.py. */
static const ModelSignatureWord model_signature[] = {
  { 0x00000000U, 0xFC98FD05U },
  { 0x00010000U, 0x02F39FDDU },
  { 0x0001A000U, 0x0EF13CDFU },
};

#define MODEL_SIGNATURE_COUNT \
  ((uint32_t)(sizeof(model_signature) / sizeof(model_signature[0])))

#endif /* MODEL_SIGNATURE_H */
