#!/usr/bin/env python3
"""Generate the runtime XSPI weight signature header from an Intel HEX file."""

import argparse
from pathlib import Path


BASE_ADDRESS = 0x70380000
SIGNATURE_OFFSETS = (0x00000, 0x10000, 0x1A000)


def read_intel_hex(path: Path) -> dict[int, int]:
    memory: dict[int, int] = {}
    upper = 0
    for line_number, raw in enumerate(path.read_text(encoding="ascii").splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        if not line.startswith(":"):
            raise ValueError(f"{path}:{line_number}: invalid Intel HEX record")
        record = bytes.fromhex(line[1:])
        length = record[0]
        address = int.from_bytes(record[1:3], "big")
        record_type = record[3]
        data = record[4:4 + length]
        if (sum(record) & 0xFF) != 0:
            raise ValueError(f"{path}:{line_number}: checksum mismatch")
        if record_type == 0x00:
            absolute = upper + address
            memory.update((absolute + index, value) for index, value in enumerate(data))
        elif record_type == 0x04:
            upper = int.from_bytes(data, "big") << 16
        elif record_type == 0x02:
            upper = int.from_bytes(data, "big") << 4
        elif record_type == 0x01:
            break
    return memory


def signature_words(memory: dict[int, int]) -> list[tuple[int, int]]:
    result = []
    for offset in SIGNATURE_OFFSETS:
        address = BASE_ADDRESS + offset
        try:
            word = bytes(memory[address + index] for index in range(4))
        except KeyError as error:
            raise ValueError(f"network data has no signature word at 0x{address:08X}") from error
        result.append((offset, int.from_bytes(word, "little")))
    return result


def render_header(words: list[tuple[int, int]]) -> str:
    entries = "\n".join(
        f"  {{ 0x{offset:08X}U, 0x{word:08X}U }}," for offset, word in words
    )
    return f"""#ifndef MODEL_SIGNATURE_H
#define MODEL_SIGNATURE_H

#include <stdint.h>

typedef struct
{{
  uint32_t offset;
  uint32_t expected;
}} ModelSignatureWord;

/* Generated by tools/generate_model_signature.py. */
static const ModelSignatureWord model_signature[] = {{
{entries}
}};

#define MODEL_SIGNATURE_COUNT \\\n  ((uint32_t)(sizeof(model_signature) / sizeof(model_signature[0])))

#endif /* MODEL_SIGNATURE_H */
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("network_hex", type=Path)
    parser.add_argument("output_header", type=Path)
    args = parser.parse_args()
    args.output_header.write_text(
        render_header(signature_words(read_intel_hex(args.network_hex))),
        encoding="ascii",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
